set -g prefix C-a
set-window-option -g mode-keys vi
if-shell "test '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -ge 4 \)'" 'bind-key -Tcopy-mode-vi v send -X begin-selection; bind-key -Tcopy-mode-vi y send -X copy-selection-and-cancel'
if-shell '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -lt 4\) -o #{$TMUX_VERSION_MAJOR} -le 1' 'bind-key -t vi-copy v begin-selection; bind-key -t vi-copy y copy-selection'
bind-key -T copy-mode-vi Enter             send-keys -X copy-pipe-and-cancel xclip
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel xclip


# Use <prefix>a
# (Prefix = Ctrl)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Mouse support
set -g mouse on
#set -g mouse-select-window on  #legacy
#set -g mouse-select-pane on    #legacy
#set -g mouse-resize-pane on    #legacy

# # Scroll History
set -g history-limit 300000

# Count sessions start at 1
set -g base-index 1

# Vi keybindings
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+
unbind [
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection

# ...after copying to a tmux buffer, hit y again to copy to clipboard
bind y run "tmux save-buffer - | reattach-to-user-namespace pbcopy"

bind N swap-window -t +1
bind P swap-window -t -1

# Reload .tmux.conf
bind R source-file ~/.tmux.conf \; display-message "  Config reloaded.."

# Hit [PREFIX]-R to reorder windows (i..e from 1-4-7-9 to 1-2-3-4 keeping the right order)
bind R                                      \
    set -g renumber-windows on\;            \
    new-window\; kill-window\;              \
    set -g renumber-windows off\;           \
    display-message "Windows reordered..."

# Rename your terminals
#set -g set-titles on
#set -g set-titles-string '#(whoami)::#h::#(curl )'
set -g automatic-rename off

# Status bar customization
# Set status bar
#set -g status-justify left
#set -g status-bg white
#set -g status-fg black
set-option -g status-interval 5
#set -g status-right-length 150
#set -g status-left ""
set -g status-right "#[fg=black] %d-%m-%Y %H:%M #(whoami)"

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Allows us to use '<prefix>-a' <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Highlight active window
# set-window-option -g window-status-current-bg red    
set-window-option -g window-status-current-style "fg=yellow,bold"
